server:
  port: 8082
spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
    vectorstore:
      pgvector:
        dimension: 1024
        distance-type: COSINE
        initialize-schema: true

  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
